#!/bin/bash

###
## Variables

declare -r actions="add|show|delete|update|suspend"
declare -r commands="domain|email|alias"

##
###

###
## Functions

  ###
  ## Helpers

  show_help() {
    echo "Usage $0 [$actions] [$commands] [options] args..."
  }

  ##
  ###

  ###
  ## Commands

  domain() {
    add() {
      echo "add"
    }
    show() {
      echo "show"
    }
    delete() {
      echo "delete"
    }
    update() {
      echo "Unimplemented"
      show_help
    }
    suspend() {
      echo "Unimplemented"
      show_help
    }
    "$1"
  }

  email() {
    add() {
      echo "add"
    }
    show() {
      echo "show"
    }
    delete() {
      echo "delete"
    }
    update() {
      echo "Unimplemented"
      show_help
    }
    suspend() {
      echo "Unimplemented"
      show_help
    }
    "$1"
  }

  alias() {
    add() {
      echo "add"
    }
    show() {
      echo "show"
    }
    delete() {
      echo "delete"
    }
    update() {
      echo "Unimplemented"
      show_help
    }
    suspend() {
      echo "Unimplemented"
      show_help
    }
    "$1"
  }
  
  ##
  ###

##
###


###
## Parsing arguments

# action
if ! [[ "$1" =~ ^($actions)$ ]]; then
  echo "Unknow action $1"
  show_help
  exit 1
fi

declare -r action="$1"

# command
if ! [[ "$2" =~ ^($commands)$ ]]; then
    echo "Unknow command $2"
    show_help
    exit 1
fi

declare -r command="$2"

##
###

###
## Main

"$command" "$action"

##
###

exit 0
