#!/bin/bash

# Copyright (C) 2010 Stéphane Robert Richard.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the project nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

###
## script directory and name

  pushd $(dirname $(readlink -f "$BASH_SOURCE")) > /dev/null
  readonly script_dir="$PWD"
  popd > /dev/null

  readonly script_name=$(basename $0)

##
###


###
## Functions
  
  ###
  ## Helpers

    # sourcing libpostadmin.sh
    source "$script_dir"/libpostadmin.sh

  ##
  ###

  ###
  ## Commands

    domains() {
      
      list() {
        if ask_help $@; then
          show_usage "$script_name list domains [matching close]
                      List domains matching [matching close]
                      The syntax of the matching close depends on the underlying SQL backend and query"
        fi

        db_query "${find_domains_query//%domain%/$domain}" | tail -n +0
      }

      if ! ask_help "$1"; then
        domain="$1"; shift
      fi

      # Main
      case "$action" in
        list)
          "$action" "$@"
        ;;
        *)
          echo Unexpected action "$action"
          show_help
          exit 1
        ;;
      esac

    }

    domain() {

      add() {
        if ask_help $@; then
          show_usage "$script_name add domain [name]
                      Add a new domain"
        fi
        domain_id=$(domain_id "$domain")
        if [ ! -z "$domain_id" ]; then
          echo domain "$domain" already exist in database
          exit 1
        fi
        db_query "${add_domain_query//%domain%/$domain}"
      }

      show() {
        if ask_help $@; then
          show_usage "$script_name show domain [name]
                      Show a domain entry"
        fi
        local result
        result=$(db_query "${show_domain_query//%domain%/$domain}")
        echo "$result"
      }

      list() {
        if ask_help $@; then
          show_usage "$script_name list domain [name]
                      List emails for this domain"
        fi
        local domain_id=$(domain_id "$domain")
        if [ -z "$domain_id" ]; then
          echo domain "$domain" does not exist in database
          exit 1
        fi
        local emails_result=$(db_query "${list_emails_query//%domain_id%/$domain_id}")
        local aliases_result=$(db_query "${list_aliases_query//%domain_id%/$domain_id}")
        echo "-- emails"
        echo "$emails_result"  | column -t
        echo "-- aliases"
        echo "$aliases_result" | awk '{print $1" -> "$2}' | column -t
      }

      delete() {
        if ask_help $@; then
          show_usage "$script_name delete domain [name]"
        fi
        domain_id=$(domain_id "$domain")
        if [ -z "$domain_id" ]; then
          echo domain "$domain" does not exist in database
          exit 1
        fi
        db_query "${delete_domain_query//%domain_id%/$domain_id}"
        rm_dir "$vmail_home" "$domain"
      }
 
      if ! ask_help "$1"; then
        if [ -z "$1" ]; then
          echo You must provide a domain
          show_help
          exit 1
        fi
        # validate args
        validate_regex "$1" "$domain_regex" 'domain'
        domain="$1"; shift
      fi

      # Main
      case "$action" in
        add|show|list|delete)
          "$action" "$@"
        ;;
        *)
          echo Unexpected action "$action"
          show_help
          exit 1
        ;;
      esac
    }

    email() {
      
      set_password() {
        
        encrypted=false
        while getopts ":e:p:" opt; do
          case $opt in
          e)
            password="$OPTARG"
            encrypted=true
          ;;
          p)
            password="$OPTARG"
          ;;
          \?)
            echo "Invalid option: -$OPTARG"
            exit 1
          ;;
          esac
        done

        if [ -z "$password" ];then
          echo "No password provided"
          show_help
          exit 1
        fi
        

        if ! $encrypted; then 
          validate_regex "$password" "$passwd_regex" 'password'
          salt=$(random_string 8)
          password=$(md5crypt_pwd "$password" "$salt")
        fi

        password=$(echo $password | sed 's/\$/\\$/g')
      }

      add() {
        if ask_help $@; then
          show_usage "$script_name add email [user@domain] ?[username] [option] [password]
                      Add email user@domain with username [username] and password [password]
                      Options:
                      p: The password in plain text
                      e: The password in encrypted form"
        fi

        user_id=$(user_id_by_email "$email")
        if [ ! -z "$user_id" ]; then
          echo email "$email" already exist in database
          exit 1
        fi

        if [[ "$1" =~ ^[^-] ]]; then
          username="$1"; shift
        else
          username="$email"
        fi

        validate_regex "$username" "$username_regex" 'username'
        username_id=$(user_id_by_username "$username")
        if [ ! -z "$username_id" ]; then
          echo username "$username" already exist in database
          exit 1
        fi

        set_password "$@"
        
        local email_query=$(substitute_tokens "$add_email_query" email username domain_id password)
        db_query "$email_query"
      }

      show() {
        if ask_help $@; then
          show_usage "$script_name show email [user@domain]
                      Show email user@domain"
        fi
        local result=$(db_query "${show_email_query//%email%/$email}")
        if [ -z "$result" ]; then
          echo email "$email" does not exist in database
        fi
        echo "$result"
      }

      delete() {
        if ask_help $@; then
          show_usage "$script_name delete email [user@domain]
                      Delete email user@domain"
        fi
        user_id=$(user_id_by_email "$email")
        if [ -z "$user_id" ]; then
          echo email "$email" does not exist in database
          exit 1
        fi
        local email_query=$(substitute_tokens "$delete_email_query" email user_id)
        db_query "$email_query"
        domain=$(domain_name "$email")
        rm_dir "$vmail_home/$domain" "${email%@$domain}"
      }

      update() {
        if ask_help $@; then
          show_usage "$script_name update email [user@domain] -[p|e] [password]
                      Update email user@domain
                      Options:
                      p: The password in plain text
                      e: The password in encrypted form"
          exit 1
        fi

        user_id=$(user_id_by_email "$email")
        if [ -z "$user_id" ]; then
          echo email "$email" does not exist in database
          exit 1
        fi

        set_password "$@"

        local email_query=$(substitute_tokens "$update_email_query" password user_id)
        db_query "$email_query"
      }

      if ! ask_help "$1"; then

        # validate args
        validate_regex "$1" "$email_regex" 'email'
        email="$1"; shift

        # retrieve domain id
        domain=$(domain_name "$email")
        domain_id=$(domain_id "$domain")

        if [ -z "$domain_id" ]; then
          echo domain "$domain" does not exist in database
          exit 1
        fi
      fi
 
      # Main
      case "$action" in
        add|show|update|delete)
          "$action" "$@"
        ;;
        *)
          echo Unexpected action "$action"
          show_help
          exit 1
        ;;
      esac
    }

    alias() {

      add() {
        if ask_help $@; then
          show_usage "$script_name add alias [source_email] [destination_email]
                      Add an alias from [source_email] to [destination_email]"
        fi

        alias_id=$(alias_id "$source_email" "$destination_email")

        if [ ! -z "$alias_id" ]; then
          echo "alias '$source_email' -> '$destination_email' already exist in database"
          exit 1
        fi

        local query=$(substitute_tokens "$add_alias_query" source_email destination_email domain_id)
        db_query "$query"
      }

      show() {
        echo "show"
      }

      delete() {
        if ask_help $@; then
          show_usage "$script_name delete alias [source_email] [destination_email]
                      Delete alias from [source_email] to [destination_email]"
        fi

        alias_id=$(alias_id "$source_email" "$destination_email")

        if [ -z "$alias_id" ]; then
          echo "alias '$source_email' -> '$destination_email' does not exist in database"
          exit 1
        fi

        db_query "${delete_alias_query//%alias_id%/$alias_id}"
      }

      if ! ask_help "$1"; then

        # validate args
        validate_regex "$1" "$alias_regex" 'source email'
        source_email="$1"; shift

        validate_regex "$1" "$alias_regex" 'destination email'
        destination_email="$1"; shift
        
        # retrieve domain id
        domain=$(domain_name "$source_email")
        domain_id=$(domain_id "$domain")

        if [ -z "$domain_id" ]; then
          echo domain "$domain" does not exist in database
          exit 1
        fi
      fi

      # Main
      case "$action" in
        add|show|delete)
          "$action" "$@"
        ;;
        *)
          echo Unexpected action "$action"
          show_help
          exit 1
        ;;
      esac
    }
    
  ##
  ###

##
###


###
## Variables
 
  # constants
  readonly actions="add|show|list|delete|update|suspend"
  readonly commands="domains|domain|email|alias"

  ##
  # Configuration variables
  
  ##CONFIG VARS -- Meta programming, do not delete
  vmail_home=/var/vmail
  debug_file="$HOME/postadmin.debug.log"

  sql_cmd='mysql -u"%sql_user%" -p"%sql_passwd%" -h"%sql_host%" -s --batch -e "USE %sql_database%; %query%"'
  sql_user=mailadmin
  sql_host=127.0.0.1
  sql_database=mailserver
  sql_passwd=mailadmin2011

  local_part_min_length=2
  local_part_max_length=23
  local_part_regex='[0-9a-z\.@_-]{%local_part_min_length%,%local_part_max_length%}'
  passwd_min_length=6
  passwd_regex='.{%passwd_min_length%,}'
  domain_regex='[a-z0-9.-]+\.[a-z]{2,4}'
  email_regex='%local_part_regex%@%domain_regex%'
  username_regex='%local_part_regex%(@%domain_regex%)?'
  alias_regex='(%local_part_regex%@)?%domain_regex%'

  user_name_min_length=1
  user_name_max_length=23
  password_min_length=6
  

  # queries
  domain_table=virtual_domains
  domain_id_column=id
  domain_name_column=name
  user_table=virtual_users
  user_id_column=id
  user_email_column=email
  user_username_column=username
  user_domain_id_column=domain_id
  user_password_column=password
  alias_table=virtual_aliases
  alias_id_column=id
  alias_domain_id_column=domain_id
  alias_source_column=source
  alias_destination_column=destination
 
  # domains
  find_domains_query="
      SELECT %domain_name_column% 
      FROM %domain_table% 
      WHERE %domain_name_column% LIKE '%domain%'"

  # domain
  domain_id_query="
      SELECT %domain_id_column% 
      FROM %domain_table% 
      WHERE %domain_name_column% = '%domain%'"
  add_domain_query="
      INSERT INTO %domain_table% (%domain_name_column%) 
      VALUES ('%domain%')"
  show_domain_query="
      SELECT %domain_name_column% 
      FROM %domain_table% 
      WHERE %domain_name_column% = '%domain%'"
  list_domains_query="
      SELECT %domain_name_column% 
      FROM %domain_table%"
  delete_domain_query="
      DELETE FROM %domain_table% 
      WHERE %domain_id_column% = %domain_id%"

  # email
  user_id_query="
      SELECT %user_id_column% 
      FROM %user_table% 
      WHERE %user_email_column% = '%email%'"
  user_id_by_username_query="
      SELECT %user_id_column% 
      FROM %user_table% 
      WHERE %user_username_column% = '%username%'"
  show_email_query="
      SELECT %user_email_column%
      FROM %user_table%
      WHERE %user_email_column% = '%email%'"
  add_email_query="
      INSERT INTO %user_table% (%user_domain_id_column%,  %user_email_column%, %user_password_column%)
      VALUES ('%domain_id%', '%email%', '%password%');
      INSERT INTO %alias_table% (%alias_domain_id_column%, %alias_source_column%, %alias_destination_column%) 
      VALUES (%domain_id%, '%email%', '%email%')"
  update_email_query="
      UPDATE %user_table%
      SET %user_password_column% = '%password%'
      WHERE %user_id_column% = '%user_id%'"
  list_emails_query="
      SELECT %user_table%.%user_email_column% 
      FROM %user_table% 
      WHERE %user_domain_id_column% = %domain_id%"
  delete_email_query="
      DELETE FROM %user_table%
      WHERE %user_id_column% = %user_id%;
      DELETE FROM %alias_table%
      WHERE %alias_source_column% = '%email%'"

  # alias
  alias_id_query="
      SELECT %alias_id_column% 
      FROM %alias_table% 
      WHERE %alias_source_column% = '%source_email%'
      AND %alias_destination_column% = '%destination_email%'"
  add_alias_query="
      INSERT INTO %alias_table% (%alias_domain_id_column%, %alias_source_column%, %alias_destination_column%) 
      VALUES (%domain_id%, '%source_email%', '%destination_email%')"
  list_aliases_query="
      SELECT %alias_source_column%, %alias_destination_column%
      FROM %alias_table%
      WHERE %alias_domain_id_column% = %domain_id%"
  delete_alias_query="
      DELETE FROM %alias_table% 
      WHERE %alias_id_column% = %alias_id%"

  ##END CONFIG VARS

  # sourcing configuration
  config_dirs="
    $script_dir
    /etc
    /usr/local/etc
    /opt/etc"

  postadmin_conf=  

  for d in $config_dirs; do
    for localdir in $d $d/postadmin; do
      if [ -d "$localdir" ] && [ -f "$localdir/postadmin.conf" ]; then
        readonly postadmin_conf="$localdir/postadmin.conf"
        break
      fi
    done
  done

  require_var "postadmin_conf" "No config file can be found in $config_dirs"
  source "$postadmin_conf"

  # assigning readonly vars
  readonly config_vars=$(grep '##CONFIG VARS' -A 100 $script_dir/$script_name\
                         | grep '##END CONFIG VARS' -B 100\
                         | egrep '^\s*[a-z0-9_]+='\
                         | sed 's/^\s*\([a-z0-9_]\+\)=.*$/\1/')
  
  for var in $config_vars; do
    if [[ "$var" =~ _regex ]]; then
      declare -r $var=$(substitute_tokens "${!var}" "$config_vars")
    else
      readonly $var
    fi
  done


##
###



###
## Parsing arguments


  # generate config file command
  case "$1" in
    'generate-config')
      for var in $config_vars; do
        value=$(echo ${!var} | sed 's/^ //')
        echo -n '#'
        if [[ "$var" =~ _query$ ]]; then
          echo $var=\"$value\" # wrap sql queries in double quotes
        else
          echo $var=$value
        fi
      done
      exit 0
    ;;
      '--help') 
        show_help; 
        exit 0
    ;;
  esac


  debug=false
  verbose=false
  for arg in $@; do
    case "$arg" in
      '--debug') readonly debug=true;;
      '--verbose') readonly verbose=true;;
    esac
  done

  if [ $# -lt 2 ]; then
    echo "Wrong argument count"
    show_help
    exit 1
  fi


  # action
  if ! [[ "$1" =~ ^($actions)$ ]]; then
    echo "Unknow action $1"
    show_help
    exit 1
  fi
  readonly action="$1"
  shift

  # command
  if ! [[ "$1" =~ ^($commands)$ ]]; then
      echo "Unknow command $1"
      show_help
      exit 1
  fi
  readonly command="$1"
  shift

##
###



###
## Main

  if $debug; then
    log_debug ========================
    log_debug DEBUGGING INFORMATIONS
    log_debug
    log_debug -- Configuration variables
    for var in $config_vars; do
      log_debug $var=${!var}
    done
    log_debug
    log_debug -- Arguments
    log_debug command=$command
    log_debug action=$action
    log_debug
    log_debug -- Additional parameters
    for arg in $@; do
      log_debug $arg
    done 
    log_debug ========================
  fi

  "$command" $@

##
###

exit 0
